# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1102, 759)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Images/water.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.inputGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.inputGroupBox.setGeometry(QtCore.QRect(10, 10, 241, 701))
        self.inputGroupBox.setAutoFillBackground(False)
        self.inputGroupBox.setFlat(False)
        self.inputGroupBox.setObjectName(_fromUtf8("inputGroupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.inputGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 671))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.inputFileList = QtGui.QListWidget(self.verticalLayoutWidget)
        self.inputFileList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.inputFileList.setIconSize(QtCore.QSize(24, 32))
        self.inputFileList.setObjectName(_fromUtf8("inputFileList"))
        self.verticalLayout.addWidget(self.inputFileList)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addImagesButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.addImagesButton.setObjectName(_fromUtf8("addImagesButton"))
        self.gridLayout.addWidget(self.addImagesButton, 1, 0, 1, 1)
        self.removeImagesButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.removeImagesButton.setObjectName(_fromUtf8("removeImagesButton"))
        self.gridLayout.addWidget(self.removeImagesButton, 1, 1, 1, 1)
        self.multiCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.multiCheckBox.setObjectName(_fromUtf8("multiCheckBox"))
        self.gridLayout.addWidget(self.multiCheckBox, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.templatingGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.templatingGroupBox.setGeometry(QtCore.QRect(250, 10, 601, 701))
        self.templatingGroupBox.setObjectName(_fromUtf8("templatingGroupBox"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.templatingGroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 581, 671))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.graphicsView = QtGui.QGraphicsView(self.verticalLayoutWidget_2)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.topFitToCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.topFitToCheckBox.setText(_fromUtf8(""))
        self.topFitToCheckBox.setChecked(True)
        self.topFitToCheckBox.setObjectName(_fromUtf8("topFitToCheckBox"))
        self.gridLayout_2.addWidget(self.topFitToCheckBox, 2, 3, 1, 1)
        self.botFitToCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.botFitToCheckBox.setText(_fromUtf8(""))
        self.botFitToCheckBox.setChecked(True)
        self.botFitToCheckBox.setObjectName(_fromUtf8("botFitToCheckBox"))
        self.gridLayout_2.addWidget(self.botFitToCheckBox, 6, 3, 1, 1)
        self.topLineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.topLineEdit.setFont(font)
        self.topLineEdit.setObjectName(_fromUtf8("topLineEdit"))
        self.gridLayout_2.addWidget(self.topLineEdit, 2, 0, 1, 1)
        self.topOpacitySpinBox = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.topOpacitySpinBox.setMaximum(1.0)
        self.topOpacitySpinBox.setSingleStep(0.05)
        self.topOpacitySpinBox.setProperty("value", 1.0)
        self.topOpacitySpinBox.setObjectName(_fromUtf8("topOpacitySpinBox"))
        self.gridLayout_2.addWidget(self.topOpacitySpinBox, 2, 4, 1, 1)
        self.centLineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.centLineEdit.setFont(font)
        self.centLineEdit.setObjectName(_fromUtf8("centLineEdit"))
        self.gridLayout_2.addWidget(self.centLineEdit, 4, 0, 1, 1)
        self.topFontButton = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.topFontButton.setObjectName(_fromUtf8("topFontButton"))
        self.gridLayout_2.addWidget(self.topFontButton, 2, 1, 1, 1)
        self.topFontSizeBox = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.topFontSizeBox.setProperty("value", 12)
        self.topFontSizeBox.setObjectName(_fromUtf8("topFontSizeBox"))
        self.gridLayout_2.addWidget(self.topFontSizeBox, 2, 2, 1, 1)
        self.topLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.topLabel.setObjectName(_fromUtf8("topLabel"))
        self.gridLayout_2.addWidget(self.topLabel, 1, 0, 1, 1)
        self.centFontButton = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.centFontButton.setObjectName(_fromUtf8("centFontButton"))
        self.gridLayout_2.addWidget(self.centFontButton, 4, 1, 1, 1)
        self.botFontButton_2 = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.botFontButton_2.setObjectName(_fromUtf8("botFontButton_2"))
        self.gridLayout_2.addWidget(self.botFontButton_2, 6, 1, 1, 1)
        self.fitToLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.fitToLabel.setObjectName(_fromUtf8("fitToLabel"))
        self.gridLayout_2.addWidget(self.fitToLabel, 0, 3, 1, 1)
        self.centFontSizeBox = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.centFontSizeBox.setProperty("value", 12)
        self.centFontSizeBox.setObjectName(_fromUtf8("centFontSizeBox"))
        self.gridLayout_2.addWidget(self.centFontSizeBox, 4, 2, 1, 1)
        self.centFitToCheckBox = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.centFitToCheckBox.setText(_fromUtf8(""))
        self.centFitToCheckBox.setChecked(True)
        self.centFitToCheckBox.setObjectName(_fromUtf8("centFitToCheckBox"))
        self.gridLayout_2.addWidget(self.centFitToCheckBox, 4, 3, 1, 1)
        self.botLineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.botLineEdit.setObjectName(_fromUtf8("botLineEdit"))
        self.gridLayout_2.addWidget(self.botLineEdit, 6, 0, 1, 1)
        self.botFontSizeBox = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.botFontSizeBox.setProperty("value", 12)
        self.botFontSizeBox.setObjectName(_fromUtf8("botFontSizeBox"))
        self.gridLayout_2.addWidget(self.botFontSizeBox, 6, 2, 1, 1)
        self.textSizeLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.textSizeLabel.setObjectName(_fromUtf8("textSizeLabel"))
        self.gridLayout_2.addWidget(self.textSizeLabel, 0, 2, 1, 1)
        self.centLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.centLabel.setObjectName(_fromUtf8("centLabel"))
        self.gridLayout_2.addWidget(self.centLabel, 3, 0, 1, 1)
        self.botLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.botLabel.setObjectName(_fromUtf8("botLabel"))
        self.gridLayout_2.addWidget(self.botLabel, 5, 0, 1, 1)
        self.opacityLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.opacityLabel.setObjectName(_fromUtf8("opacityLabel"))
        self.gridLayout_2.addWidget(self.opacityLabel, 0, 4, 1, 1)
        self.centOpacitySpinBox = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.centOpacitySpinBox.setMaximum(1.0)
        self.centOpacitySpinBox.setSingleStep(0.05)
        self.centOpacitySpinBox.setProperty("value", 1.0)
        self.centOpacitySpinBox.setObjectName(_fromUtf8("centOpacitySpinBox"))
        self.gridLayout_2.addWidget(self.centOpacitySpinBox, 4, 4, 1, 1)
        self.botOpacitySpinBox = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.botOpacitySpinBox.setMaximum(1.0)
        self.botOpacitySpinBox.setSingleStep(0.05)
        self.botOpacitySpinBox.setProperty("value", 1.0)
        self.botOpacitySpinBox.setObjectName(_fromUtf8("botOpacitySpinBox"))
        self.gridLayout_2.addWidget(self.botOpacitySpinBox, 6, 4, 1, 1)
        self.textSizeLabel_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.textSizeLabel_3.setObjectName(_fromUtf8("textSizeLabel_3"))
        self.gridLayout_2.addWidget(self.textSizeLabel_3, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.progressBar = QtGui.QProgressBar(self.verticalLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.exportButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout_2.addWidget(self.exportButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2.raise_()
        self.graphicsView.raise_()
        self.outputGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.outputGroupBox.setGeometry(QtCore.QRect(850, 10, 241, 701))
        self.outputGroupBox.setObjectName(_fromUtf8("outputGroupBox"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.outputGroupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 221, 671))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.outputFileList = QtGui.QListWidget(self.verticalLayoutWidget_3)
        self.outputFileList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.outputFileList.setIconSize(QtCore.QSize(24, 32))
        self.outputFileList.setObjectName(_fromUtf8("outputFileList"))
        self.verticalLayout_3.addWidget(self.outputFileList)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.destinationDirSelectButton = QtGui.QToolButton(self.verticalLayoutWidget_3)
        self.destinationDirSelectButton.setObjectName(_fromUtf8("destinationDirSelectButton"))
        self.gridLayout_4.addWidget(self.destinationDirSelectButton, 1, 1, 1, 1)
        self.destinationDirLineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.destinationDirLineEdit.setReadOnly(True)
        self.destinationDirLineEdit.setObjectName(_fromUtf8("destinationDirLineEdit"))
        self.gridLayout_4.addWidget(self.destinationDirLineEdit, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_Log_File = QtGui.QAction(MainWindow)
        self.actionSelect_Log_File.setObjectName(_fromUtf8("actionSelect_Log_File"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionSelect_Log_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.inputGroupBox.setTitle(_translate("MainWindow", "Input Files", None))
        self.addImagesButton.setText(_translate("MainWindow", "Add Images", None))
        self.removeImagesButton.setText(_translate("MainWindow", "Remove", None))
        self.multiCheckBox.setText(_translate("MainWindow", "Multi-Select", None))
        self.templatingGroupBox.setTitle(_translate("MainWindow", "Templating", None))
        self.topLineEdit.setText(_translate("MainWindow", "For Reference Only - Do not distribute", None))
        self.topFontButton.setText(_translate("MainWindow", "...", None))
        self.topLabel.setText(_translate("MainWindow", "Top", None))
        self.centFontButton.setText(_translate("MainWindow", "...", None))
        self.botFontButton_2.setText(_translate("MainWindow", "...", None))
        self.fitToLabel.setText(_translate("MainWindow", "Fit to ", None))
        self.textSizeLabel.setText(_translate("MainWindow", "Text Size", None))
        self.centLabel.setText(_translate("MainWindow", "Centre", None))
        self.botLabel.setText(_translate("MainWindow", "Bottom", None))
        self.opacityLabel.setText(_translate("MainWindow", "Opacity", None))
        self.textSizeLabel_3.setText(_translate("MainWindow", "Font", None))
        self.exportButton.setText(_translate("MainWindow", "Export", None))
        self.outputGroupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label.setText(_translate("MainWindow", "Destination Directory", None))
        self.destinationDirSelectButton.setText(_translate("MainWindow", "...", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSelect_Log_File.setText(_translate("MainWindow", "Select Log File...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

